//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKH.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ArticleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleInfo()
        {
            this.CommentInfo = new HashSet<CommentInfo>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public short DelFlag { get; set; }
        public int ArticleTypeId { get; set; }
        public string Summary { get; set; }
        public string Author { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentInfo> CommentInfo { get; set; }
    }
}
