//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKH.Blog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfo> AdminInfo { get; set; }
        public virtual DbSet<AdminInfoExt> AdminInfoExt { get; set; }
        public virtual DbSet<ArticleInfo> ArticleInfo { get; set; }
        public virtual DbSet<ArticleType> ArticleType { get; set; }
        public virtual DbSet<CommentInfo> CommentInfo { get; set; }
        public virtual DbSet<PhotoInfo> PhotoInfo { get; set; }
        public virtual DbSet<PhotoType> PhotoType { get; set; }
        public virtual DbSet<MessageInfo> MessageInfo { get; set; }
        public virtual DbSet<ReplyInfo> ReplyInfo { get; set; }
        public virtual DbSet<WebInfo> WebInfo { get; set; }
        public virtual DbSet<AdvertisingInfo> AdvertisingInfo { get; set; }
    }
}
