//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKH.Blog.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WebInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Creator { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Link { get; set; }
        public string Photo { get; set; }
        public string Vedio { get; set; }
        public string Logo { get; set; }
    }
}
